"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { api } from "@/lib/api";
import { useAuth } from "@/components/providers/auth-provider";
import { ErrorMessage } from "@/components/ui";

function AuthFrame({ title, subtitle, children, alternate }: { title:string;subtitle:string;children:React.ReactNode;alternate?:React.ReactNode }) { return <main className="auth-page"><section className="panel auth-panel"><Link className="brand auth-brand" href="/"><span>✦</span> HKBOARDWAR</Link><h1>{title}</h1><p className="muted">{subtitle}</p>{children}{alternate&&<p className="auth-alt">{alternate}</p>}</section></main>; }
export function LoginForm({ admin=false }: {admin?:boolean}) { const {signIn}=useAuth();const router=useRouter();const search=useSearchParams();const[error,setError]=useState<unknown>();const[loading,setLoading]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);setError(undefined);const form=new FormData(e.currentTarget);try{const session=await (admin?api.adminLogin:api.login)({email:String(form.get("email")),password:String(form.get("password"))});signIn(session);router.replace(admin?"/admin/dashboard":search.get("redirect")||"/events");}catch(reason){setError(reason);}finally{setLoading(false);}};return <AuthFrame title={admin?"Admin access":"Welcome back"} subtitle={admin?"Use an administrator account to manage the platform.":"Sign in to request a seat, host an event or view your updates."} alternate={admin?<Link href="/login">Member or host sign in</Link>:<>New to HKBOARDWAR? <Link href="/register">Create an account</Link></>}><form onSubmit={submit}><label className="field">Email<input required type="email" name="email" autoComplete="email" /></label><label className="field">Password<input required type="password" name="password" autoComplete="current-password" /></label><ErrorMessage error={error}/><button className="btn" disabled={loading}>{loading?"Signing in…":"Sign in"}</button><Link className="auth-alt" href="/forgot-password">Forgot your password?</Link></form></AuthFrame>; }
export function RegisterForm() { const {signIn}=useAuth();const router=useRouter();const[error,setError]=useState<unknown>();const[loading,setLoading]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError(undefined);const form=new FormData(e.currentTarget);const password=String(form.get("password"));if(password!==String(form.get("confirmPassword"))){setError(new Error("The two passwords do not match."));return;}setLoading(true);try{const session=await api.register({email:String(form.get("email")),nickname:String(form.get("nickname")),password,age:Number(form.get("age")),gender:String(form.get("gender"))});signIn(session);router.replace("/events");}catch(reason){setError(reason);}finally{setLoading(false);}};return <AuthFrame title="Join the table" subtitle="Create your player account. You can complete your profile after signing in." alternate={<>Already have an account? <Link href="/login">Sign in</Link></>}><form onSubmit={submit}><div className="form-grid"><label className="field full">Email<input required type="email" name="email" autoComplete="email" /></label><label className="field">Display name<input required name="nickname" maxLength={20} /></label><label className="field">Age<input required name="age" type="number" min="1" max="120" /></label><label className="field">Gender<select required name="gender" defaultValue=""><option value="" disabled>Select one</option><option value="female">Female</option><option value="male">Male</option></select></label><span/><label className="field">Password<input required minLength={8} maxLength={20} type="password" name="password" autoComplete="new-password" /></label><label className="field">Confirm password<input required minLength={8} maxLength={20} type="password" name="confirmPassword" autoComplete="new-password" /></label></div><ErrorMessage error={error}/><button className="btn orange" disabled={loading}>{loading?"Creating account…":"Create account"}</button></form></AuthFrame>; }
export function ForgotPasswordForm() { const [error,setError]=useState<unknown>();const [sent,setSent]=useState(false);const[loading,setLoading]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);setError(undefined);try{await api.forgotPassword(String(new FormData(e.currentTarget).get("email")));setSent(true);}catch(reason){setError(reason);}finally{setLoading(false);}};return <AuthFrame title="Reset password" subtitle="Enter your email. We will send a reset link if the account exists." alternate={<Link href="/login">Back to sign in</Link>}><form onSubmit={submit}><label className="field">Email<input required name="email" type="email" autoComplete="email" /></label><ErrorMessage error={error}/>{sent&&<p className="notice">If this email is registered, the reset link has been sent. Check your inbox and spam folder.</p>}<button className="btn" disabled={loading}>{loading?"Sending…":"Send reset link"}</button></form></AuthFrame>; }
export function ResetPasswordForm() { const search=useSearchParams();const token=search.get("token")||"";const[error,setError]=useState<unknown>();const[done,setDone]=useState(false);const[loading,setLoading]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const password=String(form.get("password"));if(!token){setError(new Error("This reset link has no token. Request a new reset link."));return;}if(password!==String(form.get("confirmPassword"))){setError(new Error("The two passwords do not match."));return;}setLoading(true);setError(undefined);try{await api.resetPassword(token,password);setDone(true);}catch(reason){setError(reason);}finally{setLoading(false);}};return <AuthFrame title="Choose a password" subtitle="Use a new secure password for your account." alternate={done?<Link href="/login">Continue to sign in</Link>:<Link href="/forgot-password">Request a new link</Link>}><form onSubmit={submit}><label className="field">New password<input required minLength={8} name="password" type="password" autoComplete="new-password" /></label><label className="field">Confirm password<input required minLength={8} name="confirmPassword" type="password" autoComplete="new-password" /></label><ErrorMessage error={error}/>{done&&<p className="notice">Password changed. You can now sign in.</p>}<button className="btn" disabled={loading||done}>{loading?"Saving…":"Save new password"}</button></form></AuthFrame>; }
