"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { RequireAuth } from "@/components/auth-guard";
import { ErrorMessage, Notice, Status, useToast } from "@/components/ui";
import { api, apiBaseUrl } from "@/lib/api";
import { getToken, saveUser } from "@/lib/auth-store";
import { useAuth } from "@/components/providers/auth-provider";
import type { NotificationItem, PendingRating, Registration } from "@/lib/types";
import { eventOf, formatDate, idOf, listOf, readableCategory } from "@/lib/utils";

export function HistoryPage() {
  const [items,setItems]=useState<Registration[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<unknown>();
  const load=useCallback(async()=>{setLoading(true);try{setItems(listOf(await api.history({})));}catch(reason){setError(reason);}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  return <RequireAuth><AppShell><main className="page shell"><div className="page-intro"><div className="eyebrow">My activity</div><h1 className="page-title">Event history</h1><p className="lead">Your previous sessions and any ratings still waiting for you.</p></div><ErrorMessage error={error}/>{loading?<div className="empty">Loading history…</div>:items.length?<div className="grid-2">{items.map(item=>{const event=eventOf(item);return <article className="panel" key={item.registrationId||idOf(item)}><div className="event-meta"><Status value={item.ratingStatus||item.requestStatus}/><span>{readableCategory(event?.boardgameCategory)}</span></div><h3 style={{margin:"14px 0 8px"}}>{event?.eventTitle||"Event"}</h3><p className="muted">{formatDate(event?.eventStartTime)} · {event?.boardgameName}</p><div className="button-row" style={{marginTop:18}}>{event&&<Link className="btn small secondary" href={`/events/${idOf(event)}`}>Details</Link>}{event&&item.ratingStatus==="pending"&&<Link className="btn small ghost" href={`/my/history/${idOf(event)}/rate`}>Rate players</Link>}</div></article>;})}</div>:<div className="empty">No past event history yet.</div>}</main></AppShell></RequireAuth>;
}

export function RatingPage({ eventId }: {eventId:string}) {
  const [pending,setPending]=useState<PendingRating|null>(null); const [values,setValues]=useState<Record<string,0|1>>({}); const [error,setError]=useState<unknown>(); const [loading,setLoading]=useState(true); const {toast,show}=useToast();
  useEffect(()=>{(async()=>{setLoading(true);try{const list=listOf(await api.pendingRatings());const found=list.find(item=>item.eventId===eventId)||null;setPending(found);if(found){const initial:Record<string,0|1>={};found.targets.forEach(person=>initial[person.userId]=1);setValues(initial);}}catch(reason){setError(reason);}finally{setLoading(false);}})();},[eventId]);
  const submit=async()=>{if(!pending)return; if(pending.targets.some(person=>values[person.userId]===undefined)){setError(new Error("Rate every listed player before submitting."));return;}try{await api.rate(eventId,pending.targets.map(person=>({rateeId:person.userId,value:values[person.userId]})));show("Ratings submitted. Thank you for helping keep tables welcoming.");setPending(null);}catch(reason){setError(reason);}};
  return <RequireAuth><AppShell><main className="page shell"><div className="page-intro"><div className="eyebrow">After the game</div><h1 className="page-title">Rate your table</h1></div><ErrorMessage error={error}/>{loading?<div className="empty">Loading rating task…</div>:!pending?<div className="empty">This event has no pending rating task, or it has already been completed.</div>:<section className="panel"><h2>{pending.eventTitle}</h2><p className="muted" style={{margin:"8px 0 22px"}}>Choose “positive” or “not positive” for every player. The frontend sends the required API values: 1 or 0.</p><div className="table-wrap"><table><thead><tr><th>Player</th><th>Rating</th></tr></thead><tbody>{pending.targets.map(person=><tr key={person.userId}><td>{person.nickname}</td><td><div className="button-row"><button className={`btn small ${values[person.userId]===1?"":"ghost"}`} onClick={()=>setValues({...values,[person.userId]:1})}>Positive +1</button><button className={`btn small ${values[person.userId]===0?"danger":"ghost"}`} onClick={()=>setValues({...values,[person.userId]:0})}>Not positive +0</button></div></td></tr>)}</tbody></table></div><div className="button-row" style={{marginTop:22}}><button className="btn orange" onClick={()=>void submit()}>Submit all ratings</button><Link className="btn secondary" href="/my/history">Back to history</Link></div></section>}</main>{toast}</AppShell></RequireAuth>;
}

export function ProfilePage() {
  const {user,refresh}=useAuth(); const [error,setError]=useState<unknown>(); const [success,setSuccess]=useState("");
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError(undefined);setSuccess("");const form=new FormData(e.currentTarget);try{const updated=await api.updateMe({nickname:String(form.get("nickname")),age:Number(form.get("age")),gender:String(form.get("gender")),intro:String(form.get("intro"))});saveUser(updated);await refresh();setSuccess("Profile saved.");}catch(reason){setError(reason);}};
  return <RequireAuth><AppShell><main className="page shell"><div className="page-intro"><div className="eyebrow">Account</div><h1 className="page-title">My profile</h1><p className="lead">Your visible name and player information. Avatar uploading is intentionally not included because the current backend has no avatar API.</p></div><section className="two-col"><form className="panel" onSubmit={submit}><div className="form-grid"><label className="field">Display name<input name="nickname" required minLength={2} maxLength={20} defaultValue={user?.nickname}/></label><label className="field">Email<input value={user?.email||""} disabled/></label><label className="field">Age<input name="age" required type="number" min="1" max="120" defaultValue={user?.age}/></label><label className="field">Gender<select name="gender" defaultValue={user?.gender||"female"}><option value="female">Female</option><option value="male">Male</option></select></label><label className="field full">Introduction<textarea name="intro" maxLength={200} defaultValue={user?.intro||""} placeholder="A short introduction for your hosts and teammates."/></label></div><ErrorMessage error={error}/>{success&&<Notice>{success}</Notice>}<button className="btn" style={{marginTop:16}}>Save profile</button></form><aside className="panel"><h3>Account shortcuts</h3><div className="sidebar-row"><span>Role</span><b>{user?.role}</b></div><div className="sidebar-row"><span>Player level</span><b>{user?.level ?? "—"}</b></div><div className="button-row" style={{marginTop:20}}><Link className="btn small secondary" href="/my/profile/notificationssetting">Notification settings</Link><Link className="btn small ghost" href="/my/registration">My registrations</Link></div></aside></section></main></AppShell></RequireAuth>;
}

export function NotificationSettingsPage() {
  const {user,refresh}=useAuth(); const [site,setSite]=useState(Boolean(user?.notifySite)); const [email,setEmail]=useState(Boolean(user?.notifyEmail)); const [error,setError]=useState<unknown>(); const [success,setSuccess]=useState("");
  useEffect(()=>{setSite(user?.notifySite!==false);setEmail(user?.notifyEmail!==false);},[user]);
  const save=async()=>{try{const updated=await api.updateNotifications({notifySite:site,notifyEmail:email});saveUser(updated);await refresh();setSuccess("Notification preferences saved.");}catch(reason){setError(reason);}};
  return <RequireAuth><AppShell><main className="page shell"><div className="page-intro"><div className="eyebrow">Account</div><h1 className="page-title">Notifications</h1><p className="lead">Choose how you hear about registration updates and event changes.</p></div><section className="panel" style={{maxWidth:720}}><label className="sidebar-row"><span><b>In-platform notifications</b><br/><small>Updates appear inside HKBOARDWAR.</small></span><input type="checkbox" checked={site} onChange={e=>setSite(e.target.checked)}/></label><label className="sidebar-row"><span><b>Email notifications</b><br/><small>Requires SMTP to be set correctly on Render.</small></span><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/></label><ErrorMessage error={error}/>{success&&<Notice>{success}</Notice>}<div className="button-row" style={{marginTop:20}}><button className="btn" onClick={()=>void save()}>Save settings</button><Link className="btn secondary" href="/my/profile">Back to profile</Link></div></section></main></AppShell></RequireAuth>;
}

function useSseNotifications(onIncoming:()=>void) {
  const token=getToken();
  useEffect(()=>{if(!token||process.env.NEXT_PUBLIC_ENABLE_SSE==="false")return;let stream:EventSource|undefined;let reconnect:number|undefined;let closed=false;const retry=()=>{if(!closed)reconnect=window.setTimeout(()=>void connect(),5000);};const connect=async()=>{try{const ticket=await api.createSseToken();if(closed)return;stream=new EventSource(`${apiBaseUrl}/api/notifications/stream?sseToken=${encodeURIComponent(ticket.sseToken)}`);stream.onmessage=()=>onIncoming();stream.onerror=()=>{stream?.close();retry();};}catch{retry();}};void connect();return()=>{closed=true;stream?.close();if(reconnect)window.clearTimeout(reconnect);};},[token,onIncoming]);
}

export function NotificationsPage() {
  const [items,setItems]=useState<NotificationItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<unknown>();
  const load=useCallback(async()=>{try{const result=await api.notifications();setItems(listOf(result));}catch(reason){setError(reason);}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]); useSseNotifications(load);
  return <RequireAuth><AppShell><main className="page shell"><div className="page-intro"><div className="eyebrow">My activity</div><h1 className="page-title">Notifications</h1><p className="lead">New in-platform notifications appear here. With SSE enabled, this list refreshes automatically when the server sends an event.</p></div><ErrorMessage error={error}/>{loading?<div className="empty">Loading notifications…</div>:items.length?<section className="panel">{items.map(item=><article key={idOf(item)} className="sidebar-row"><span><b>{item.title||item.type||"Platform update"}</b><br/><small>{item.content||item.message||"You have a new update."}</small></span><small>{formatDate(item.createdAt)}</small></article>)}</section>:<div className="empty">You have no notifications yet.</div>}</main></AppShell></RequireAuth>;
}
