"use client";

import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { EventCard } from "@/components/ui";
import { useAuth } from "@/components/providers/auth-provider";
import type { EventItem } from "@/lib/types";

const showcase: EventItem[] = [
  { _id:"demo-light", eventTitle:"Saturday City Builders", boardgameName:"Ticket to Ride",boardgameCategory:"light",description:"",address:{district:"Kowloon"},levelSetUp:{levelRangeMin:2,levelRangeMax:4},capacity:6,joinedCount:4,eventStartTime:"2026-10-03T05:00:00.000Z",eventEndTime:"2026-10-03T08:00:00.000Z",eventStatus:"published" },
  { _id:"demo-heavy", eventTitle:"Engine Night: Full Table", boardgameName:"Brass: Birmingham",boardgameCategory:"heavy",description:"",address:{district:"Central"},levelSetUp:{levelRangeMin:4,levelRangeMax:7},capacity:4,joinedCount:3,eventStartTime:"2026-10-08T11:00:00.000Z",eventEndTime:"2026-10-08T15:00:00.000Z",eventStatus:"published" },
  { _id:"demo-tcg", eventTitle:"TCG Open Play Lab", boardgameName:"Magic: The Gathering",boardgameCategory:"tcg",description:"",address:{district:"Mong Kok"},levelSetUp:{levelRangeMin:2,levelRangeMax:6},capacity:12,joinedCount:8,eventStartTime:"2026-10-11T06:00:00.000Z",eventEndTime:"2026-10-11T09:00:00.000Z",eventStatus:"published" },
];
const categories=[{key:"light",title:"Light",copy:"Easy to learn, social to play. Meet new teammates without a long rules briefing."},{key:"heavy",title:"Heavy",copy:"Deep strategy for players who enjoy focused sessions and decisive teamwork."},{key:"tcg",title:"TCG",copy:"Find a table for decks, trading, casual matches and organised play."}];

export default function HomePage() {
  const { user }=useAuth(); const destination=user?"/events":"/login?redirect=%2Fevents";
  return <AppShell><main><section className="hero"><div className="hero-game-stack" aria-hidden="true"><div className="hero-game one"><span>Light table</span><strong>GO</strong></div><div className="hero-game two"><span>Heavy table</span><strong>PLAY</strong></div><div className="hero-game three"><span>TCG night</span><strong>WIN</strong></div></div><div className="shell hero-copy"><div className="eyebrow">Hong Kong board game events</div><h1 className="hero-title">Find your <span className="cyan">team.</span><br/>Play your <span className="orange">game.</span></h1><p>HKBOARDWAR brings players and hosts together for clear, welcoming board game events across Hong Kong.</p><div className="button-row"><Link className="btn" href={destination}>Find my team</Link><Link className="btn secondary" href={destination}>Explore events</Link></div></div></section><section className="section" id="events"><div className="shell"><div className="section-head"><div><div className="eyebrow">Ready tables</div><h2 className="section-title">Hot events</h2></div><Link className="btn small ghost" href={destination}>View all events</Link></div><div className="event-grid">{showcase.map(event=><EventCard key={event._id} event={event} action={<Link className="btn small secondary" href={destination}>Join the table</Link>}/>)}</div></div></section><section className="section" id="categories"><div className="shell"><div className="section-head"><div><div className="eyebrow">Choose your pace</div><h2 className="section-title">Three ways to play</h2></div><p className="lead">Choose a category, discover an event, then join a team that is right for your experience level.</p></div><div className="grid-3">{categories.map(category=><article className={`category-card ${category.key}`} key={category.key}><div className="eyebrow">Category</div><h3>{category.title}</h3><p>{category.copy}</p><Link className="btn small secondary" href={destination}>See {category.title} events</Link></article>)}</div></div></section><section className="section" id="how-it-works"><div className="shell panel"><div className="eyebrow">One move to join a team</div><h2 className="section-title">From event to table</h2><div className="steps"><div className="step"><div className="step-number">01</div><h3>Browse your fit</h3><p>Filter by game type, level, date and location.</p></div><div className="step"><div className="step-number">02</div><h3>Send your request</h3><p>Add a short note and let the host review your request.</p></div><div className="step"><div className="step-number">03</div><h3>Show up & play</h3><p>Get a status notification, meet your table and rate the session after.</p></div></div><div className="button-row" style={{marginTop:32}}><Link className="btn orange" href={destination}>Start exploring</Link></div></div></section></main></AppShell>;
}
